MAIL_SERVER = 'email-smtp.us-east-2.amazonaws.com'
MAIL_PORT = 587
MAIL_USE_TLS = True
# MAIL_USE_SSL = True
MAIL_USERNAME = 'AKIATQHBHXEKDHN773HA'
MAIL_PASSWORD = 'BIxCGPyyMPNI7S8Qn/RgVZ6IzWCdCsYNerLd5AMAx67f'
MAIL_DEFAULT_SENDER = 'envio@libellum.co'